#pragma once

#include "based/macro/get_macro.hpp"

// NOLINTBEGIN(*macro-usage*)

// clang-format off
#define BASED_FE_0_1(First, WHAT)
#define BASED_FE_1_1(First, WHAT, X)       WHAT(First, X, 0)
#define BASED_FE_2_1(First, WHAT, X, ...)  WHAT(First, X, 1)  BASED_FE_1_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_3_1(First, WHAT, X, ...)  WHAT(First, X, 2)  BASED_FE_2_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_4_1(First, WHAT, X, ...)  WHAT(First, X, 3)  BASED_FE_3_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_5_1(First, WHAT, X, ...)  WHAT(First, X, 4)  BASED_FE_4_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_6_1(First, WHAT, X, ...)  WHAT(First, X, 5)  BASED_FE_5_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_7_1(First, WHAT, X, ...)  WHAT(First, X, 6)  BASED_FE_6_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_8_1(First, WHAT, X, ...)  WHAT(First, X, 7)  BASED_FE_7_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_9_1(First, WHAT, X, ...)  WHAT(First, X, 8)  BASED_FE_8_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_10_1(First, WHAT, X, ...) WHAT(First, X, 9)  BASED_FE_9_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_11_1(First, WHAT, X, ...) WHAT(First, X, 10) BASED_FE_10_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_12_1(First, WHAT, X, ...) WHAT(First, X, 11) BASED_FE_11_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_13_1(First, WHAT, X, ...) WHAT(First, X, 12) BASED_FE_12_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_14_1(First, WHAT, X, ...) WHAT(First, X, 13) BASED_FE_13_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_15_1(First, WHAT, X, ...) WHAT(First, X, 14) BASED_FE_14_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_16_1(First, WHAT, X, ...) WHAT(First, X, 15) BASED_FE_15_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_17_1(First, WHAT, X, ...) WHAT(First, X, 16) BASED_FE_16_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_18_1(First, WHAT, X, ...) WHAT(First, X, 17) BASED_FE_17_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_19_1(First, WHAT, X, ...) WHAT(First, X, 18) BASED_FE_18_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_20_1(First, WHAT, X, ...) WHAT(First, X, 19) BASED_FE_19_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_21_1(First, WHAT, X, ...) WHAT(First, X, 20) BASED_FE_20_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_22_1(First, WHAT, X, ...) WHAT(First, X, 21) BASED_FE_21_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_23_1(First, WHAT, X, ...) WHAT(First, X, 22) BASED_FE_22_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_24_1(First, WHAT, X, ...) WHAT(First, X, 23) BASED_FE_23_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_25_1(First, WHAT, X, ...) WHAT(First, X, 24) BASED_FE_24_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_26_1(First, WHAT, X, ...) WHAT(First, X, 25) BASED_FE_25_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_27_1(First, WHAT, X, ...) WHAT(First, X, 26) BASED_FE_26_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_28_1(First, WHAT, X, ...) WHAT(First, X, 27) BASED_FE_27_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_29_1(First, WHAT, X, ...) WHAT(First, X, 28) BASED_FE_28_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_30_1(First, WHAT, X, ...) WHAT(First, X, 29) BASED_FE_29_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_31_1(First, WHAT, X, ...) WHAT(First, X, 30) BASED_FE_30_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_32_1(First, WHAT, X, ...) WHAT(First, X, 31) BASED_FE_31_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_33_1(First, WHAT, X, ...) WHAT(First, X, 32) BASED_FE_32_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_34_1(First, WHAT, X, ...) WHAT(First, X, 33) BASED_FE_33_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_35_1(First, WHAT, X, ...) WHAT(First, X, 34) BASED_FE_34_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_36_1(First, WHAT, X, ...) WHAT(First, X, 35) BASED_FE_35_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_37_1(First, WHAT, X, ...) WHAT(First, X, 36) BASED_FE_36_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_38_1(First, WHAT, X, ...) WHAT(First, X, 37) BASED_FE_37_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_39_1(First, WHAT, X, ...) WHAT(First, X, 38) BASED_FE_38_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_40_1(First, WHAT, X, ...) WHAT(First, X, 39) BASED_FE_39_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_41_1(First, WHAT, X, ...) WHAT(First, X, 40) BASED_FE_40_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_42_1(First, WHAT, X, ...) WHAT(First, X, 41) BASED_FE_41_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_43_1(First, WHAT, X, ...) WHAT(First, X, 42) BASED_FE_42_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_44_1(First, WHAT, X, ...) WHAT(First, X, 43) BASED_FE_43_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_45_1(First, WHAT, X, ...) WHAT(First, X, 44) BASED_FE_44_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_46_1(First, WHAT, X, ...) WHAT(First, X, 45) BASED_FE_45_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_47_1(First, WHAT, X, ...) WHAT(First, X, 46) BASED_FE_46_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_48_1(First, WHAT, X, ...) WHAT(First, X, 47) BASED_FE_47_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_49_1(First, WHAT, X, ...) WHAT(First, X, 48) BASED_FE_48_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_50_1(First, WHAT, X, ...) WHAT(First, X, 49) BASED_FE_49_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_51_1(First, WHAT, X, ...) WHAT(First, X, 50) BASED_FE_50_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_52_1(First, WHAT, X, ...) WHAT(First, X, 51) BASED_FE_51_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_53_1(First, WHAT, X, ...) WHAT(First, X, 52) BASED_FE_52_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_54_1(First, WHAT, X, ...) WHAT(First, X, 53) BASED_FE_53_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_55_1(First, WHAT, X, ...) WHAT(First, X, 54) BASED_FE_60_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_56_1(First, WHAT, X, ...) WHAT(First, X, 55) BASED_FE_61_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_57_1(First, WHAT, X, ...) WHAT(First, X, 56) BASED_FE_62_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_58_1(First, WHAT, X, ...) WHAT(First, X, 57) BASED_FE_57_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_59_1(First, WHAT, X, ...) WHAT(First, X, 58) BASED_FE_58_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_60_1(First, WHAT, X, ...) WHAT(First, X, 59) BASED_FE_59_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_61_1(First, WHAT, X, ...) WHAT(First, X, 60) BASED_FE_60_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_62_1(First, WHAT, X, ...) WHAT(First, X, 61) BASED_FE_61_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_63_1(First, WHAT, X, ...) WHAT(First, X, 62) BASED_FE_62_1(First, WHAT, __VA_ARGS__)
#define BASED_FE_64_1(First, WHAT, X, ...) WHAT(First, X, 63) BASED_FE_63_1(First, WHAT, __VA_ARGS__)
// clang-format on

#define BASED_FOREACH_1(First, action, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
  BASED_GET_MACRO(_0, __VA_ARGS__, BASED_FE_64_1, BASED_FE_63_1, BASED_FE_62_1, BASED_FE_61_1, BASED_FE_60_1, BASED_FE_59_1, BASED_FE_58_1, BASED_FE_57_1, BASED_FE_56_1, BASED_FE_55_1, BASED_FE_54_1, BASED_FE_53_1, BASED_FE_52_1, BASED_FE_51_1, BASED_FE_50_1, BASED_FE_49_1, BASED_FE_48_1, BASED_FE_47_1, BASED_FE_46_1, BASED_FE_45_1, BASED_FE_44_1, BASED_FE_43_1, BASED_FE_42_1, BASED_FE_41_1, BASED_FE_40_1, BASED_FE_39_1, BASED_FE_38_1, BASED_FE_37_1, BASED_FE_36_1, BASED_FE_35_1, BASED_FE_34_1, BASED_FE_33_1, BASED_FE_32_1, BASED_FE_31_1, BASED_FE_30_1, BASED_FE_29_1, BASED_FE_28_1, BASED_FE_27_1, BASED_FE_26_1, BASED_FE_25_1, BASED_FE_24_1, BASED_FE_23_1, BASED_FE_22_1, BASED_FE_21_1, BASED_FE_20_1, BASED_FE_19_1, BASED_FE_18_1, BASED_FE_17_1, BASED_FE_16_1, BASED_FE_15_1, BASED_FE_14_1, BASED_FE_13_1, BASED_FE_12_1, BASED_FE_11_1, BASED_FE_10_1, BASED_FE_9_1, BASED_FE_8_1, BASED_FE_7_1, BASED_FE_6_1, BASED_FE_5_1, BASED_FE_4_1, BASED_FE_3_1, BASED_FE_2_1, BASED_FE_1_1, BASED_FE_0_1)( \
      First, action, __VA_ARGS__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
  )

// NOLINTEND(*macro-usage*)
