#pragma once

#include "based/macro/get_macro.hpp"

// NOLINTBEGIN(*macro-usage*)

// clang-format off
#define BASED_FE_0_2(First, Second, WHAT)
#define BASED_FE_1_2(First, Second, WHAT, X)       WHAT(First, Second, X, 0)
#define BASED_FE_2_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 1)  BASED_FE_1_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_3_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 2)  BASED_FE_2_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_4_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 3)  BASED_FE_3_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_5_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 4)  BASED_FE_4_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_6_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 5)  BASED_FE_5_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_7_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 6)  BASED_FE_6_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_8_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 7)  BASED_FE_7_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_9_2(First, Second, WHAT, X, ...)  WHAT(First, Second, X, 8)  BASED_FE_8_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_10_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 9)  BASED_FE_9_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_11_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 10) BASED_FE_10_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_12_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 11) BASED_FE_11_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_13_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 12) BASED_FE_12_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_14_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 13) BASED_FE_13_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_15_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 14) BASED_FE_14_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_16_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 15) BASED_FE_15_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_17_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 16) BASED_FE_16_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_18_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 17) BASED_FE_17_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_19_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 18) BASED_FE_18_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_20_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 19) BASED_FE_19_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_21_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 20) BASED_FE_20_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_22_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 21) BASED_FE_21_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_23_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 22) BASED_FE_22_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_24_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 23) BASED_FE_23_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_25_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 24) BASED_FE_24_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_26_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 25) BASED_FE_25_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_27_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 26) BASED_FE_26_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_28_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 27) BASED_FE_27_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_29_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 28) BASED_FE_28_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_30_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 29) BASED_FE_29_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_31_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 30) BASED_FE_30_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_32_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 31) BASED_FE_31_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_33_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 32) BASED_FE_32_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_34_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 33) BASED_FE_33_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_35_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 34) BASED_FE_34_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_36_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 35) BASED_FE_35_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_37_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 36) BASED_FE_36_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_38_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 37) BASED_FE_37_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_39_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 38) BASED_FE_38_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_40_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 39) BASED_FE_39_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_41_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 40) BASED_FE_40_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_42_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 41) BASED_FE_41_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_43_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 42) BASED_FE_42_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_44_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 43) BASED_FE_43_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_45_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 44) BASED_FE_44_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_46_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 45) BASED_FE_45_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_47_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 46) BASED_FE_46_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_48_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 47) BASED_FE_47_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_49_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 48) BASED_FE_48_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_50_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 49) BASED_FE_49_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_51_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 50) BASED_FE_50_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_52_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 51) BASED_FE_51_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_53_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 52) BASED_FE_52_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_54_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 53) BASED_FE_53_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_55_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 54) BASED_FE_54_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_56_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 55) BASED_FE_55_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_57_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 56) BASED_FE_56_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_58_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 57) BASED_FE_57_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_59_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 58) BASED_FE_58_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_60_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 59) BASED_FE_59_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_61_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 60) BASED_FE_60_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_62_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 61) BASED_FE_61_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_63_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 62) BASED_FE_62_2(First, Second, WHAT, __VA_ARGS__)
#define BASED_FE_64_2(First, Second, WHAT, X, ...) WHAT(First, Second, X, 63) BASED_FE_63_2(First, Second, WHAT, __VA_ARGS__)
// clang-format on

#define BASED_FOREACH_2(First, Second, action, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
  BASED_GET_MACRO(_0, __VA_ARGS__, BASED_FE_64_2, BASED_FE_63_2, BASED_FE_62_2, BASED_FE_61_2, BASED_FE_60_2, BASED_FE_59_2, BASED_FE_58_2, BASED_FE_57_2, BASED_FE_56_2, BASED_FE_55_2, BASED_FE_54_2, BASED_FE_53_2, BASED_FE_52_2, BASED_FE_51_2, BASED_FE_50_2, BASED_FE_49_2, BASED_FE_48_2, BASED_FE_47_2, BASED_FE_46_2, BASED_FE_45_2, BASED_FE_44_2, BASED_FE_43_2, BASED_FE_42_2, BASED_FE_41_2, BASED_FE_40_2, BASED_FE_39_2, BASED_FE_38_2, BASED_FE_37_2, BASED_FE_36_2, BASED_FE_35_2, BASED_FE_34_2, BASED_FE_33_2, BASED_FE_32_2, BASED_FE_31_2, BASED_FE_30_2, BASED_FE_29_2, BASED_FE_28_2, BASED_FE_27_2, BASED_FE_26_2, BASED_FE_25_2, BASED_FE_24_2, BASED_FE_23_2, BASED_FE_22_2, BASED_FE_21_2, BASED_FE_20_2, BASED_FE_19_2, BASED_FE_18_2, BASED_FE_17_2, BASED_FE_16_2, BASED_FE_15_2, BASED_FE_14_2, BASED_FE_13_2, BASED_FE_12_2, BASED_FE_11_2, BASED_FE_10_2, BASED_FE_9_2, BASED_FE_8_2, BASED_FE_7_2, BASED_FE_6_2, BASED_FE_5_2, BASED_FE_4_2, BASED_FE_3_2, BASED_FE_2_2, BASED_FE_1_2, BASED_FE_0_2)( \
      First, Second, action, __VA_ARGS__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  )

// NOLINTEND(*macro-usage*)
